### ISSUE TITLE
Mat-list-touch rename + module update ng9

### ISSUE THREAD

**Issue by davidzwa** [ShankyTiwari/ng-swipe-to-delete#9]
The new update has been merged. Need to update npm if the update is verified to be what this was intended for.

If not I will create a new NPM package as the name has changed anyway.

**Comment by riwos** [comment]
It would be nice to update NPM because that one doesn't work.. 'npm install --save mat-list-touch'

**Comment by davidzwa** [comment]
I have asked the owner, not gotten a reaction so far. Will wait a bit and then if required create my own NPM repo!

`mat-list-touch` does not exist yet.

**Comment by riwos** [comment]
@davidzwa sounds good :) @ShankyTiwari maybe you will be able to update NPM mate ;) give us a shout when you do it

**Comment by davidzwa** [comment]
I think our friend is quite busy. Will make sure to move it to another repo with another npm package. Please bear with me.

The package will be called mat-list-touch and will revolve around Angular 10 with slight interface changes.

**Comment by riwos** [comment]
@davidzwa just let me know if you need a hand and when you publish on NPM. Thanks mate !!

**Comment by ShankyTiwari** [comment]
Sorry guys, I will update the repo & npm tomorrow for sure. I am quite busy with my day job.

**Comment by ShankyTiwari** [comment]
I have updated the repo name tomorrow I will update it on NPM as well  @davidzwa

**Comment by davidzwa** [comment]
Absolute hero

**Comment by ShankyTiwari** [comment]
@davidzwa No man, you are hero. You have been working on this from very long. Now I will make sure to give some time on this project, let's make it success.

Hi @riwos thanks for showing interest into the package, here is [npm link.](https://www.npmjs.com/package/mat-list-touch). Please download it and let us know if you have issues. 

_I haven't downloaded/tested package from NPM since it's 4AM in India, I'll have some sleep now._

Thanks,
